# Introduction to Numpy

In [4]:
import numpy as np

In [10]:
my_list=[1,2,3,4]


### Create An Array

In [ ]:
arr = np.array(my_list)

In [11]:
arr.shape   # Print the shape of an array ( #Rows, #Col)

(4,)

In [7]:
arr

array([1, 2, 3, 4])

In [8]:
print(arr)

[1 2 3 4]


#### 2D Array


In [12]:
my_list1=[1,2,3,4]
my_list2=[5,6,7,8]
my_list3=[9,10,11,12]

In [13]:
arr2d = np.array([my_list1,my_list2,my_list3])

In [14]:
arr2d.shape


(3, 4)

In [15]:
arr2d.reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

#### Converting 2d Array to 1D array

In [16]:
arr2d.reshape(12,)   

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

### Indexing


In [17]:
arr2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [18]:
arr2d[2]

array([ 9, 10, 11, 12])

In [20]:
arr2d[2:,:-1]

array([[ 9, 10, 11]])

## In-built functions

#### Arrange
Return 1D Array - evenly spaced values withinn an interval 

In [27]:
np.arange(2,10,step=2)

array([2, 4, 6, 8])

#### linspace

From start and end , how many points you want? equally spaced points

In [32]:
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])