# Introduction to Numpy

In [2]:
import numpy as np

In [3]:
my_list=[1,2,3,4]


### Create An Array

In [4]:
arr = np.array(my_list)

In [5]:
arr.shape   # Print the shape of an array ( #Rows, #Col)

(4,)

In [6]:
arr

array([1, 2, 3, 4])

In [7]:
print(arr)

[1 2 3 4]


#### 2D Array


In [8]:
my_list1=[1,2,3,4]
my_list2=[5,6,7,8]
my_list3=[9,10,11,12]

In [9]:
arr2d = np.array([my_list1,my_list2,my_list3])

In [10]:
arr2d.shape


(3, 4)

In [11]:
arr2d.reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

#### Converting 2d Array to 1D array

In [12]:
arr2d.reshape(12,)   

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

### Indexing


In [13]:
arr2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [14]:
arr2d[2]

array([ 9, 10, 11, 12])

In [15]:
arr2d[2:,:-1]

array([[ 9, 10, 11]])

## In-built functions

#### Arange
Return 1D Array - evenly spaced values withinn an interval 

arange(star,end,step)

In [16]:
np.arange(2,10,step=2)

array([2, 4, 6, 8])

#### linspace

From start and end , how many points you want? equally spaced points

In [17]:
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

#### copy function

if arr==arr1  the copy is reference type. 

In [19]:
arr3 = arr2d.copy()
arr3

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

#### Ones

Create arrays with all elements as `1`s


In [30]:
np.ones((2,4),dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

#### Random Distribution

1. rand

    for a (row,col) shape given  output numbers in (0,1)
    np.random.rand()

In [31]:
np.random.rand(3,3)

array([[0.76572148, 0.29621801, 0.61000967],
       [0.94259235, 0.03852071, 0.85626293],
       [0.25384551, 0.88094574, 0.84197697]])

2.  randn 

    Return a sample from "standard normal" distribution

In [32]:
np.random.randn(3,3)

array([[-0.05099802, -0.49107265,  0.39571555],
       [-2.45914126,  0.36893298, -0.35384592],
       [-1.07575145,  1.00399094,  1.25094383]])

3.  randint

    Return random integers from [ low, high ] with size 
    randint (low,high,size)

In [36]:
np.random.randint(0,100,8).reshape(4,2)

array([[62, 51],
       [ 3, 83],
       [58,  3],
       [40, 99]])

4.  Random sample

    return random floats in half open interval [0.0,1.0) with size

In [43]:
np.random.random_sample(size=(5,5))

array([[0.24659587, 0.81113637, 0.02910338, 0.02588989, 0.36567568],
       [0.64539205, 0.93190857, 0.36974557, 0.32247572, 0.16909694],
       [0.63087226, 0.62649271, 0.20528093, 0.81880532, 0.32232899],
       [0.31026684, 0.97300757, 0.56663111, 0.57457532, 0.86408741],
       [0.68621215, 0.30355785, 0.44634379, 0.63956169, 0.44493646]])

### Conditions Useful In Exploratory Data Analysis

Arithematic Operations on all elemets in the array 

Suppose `val` = 2

In [26]:
val =2


In [27]:
arr3*val

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24]])

In [28]:
arr3/val

array([[0.5, 1. , 1.5, 2. ],
       [2.5, 3. , 3.5, 4. ],
       [4.5, 5. , 5.5, 6. ]])

Checking is each elemets is less that certain `val`

In [29]:
arr3<val

array([[ True, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [25]:
arr3[arr3<val]

array([1])